import type { INodeProperties } from 'n8n-workflow';

export const customerIdProperty: INodeProperties = {
	displayName: 'Customer ID',
	description: 'Customer ID in CCP',
	name: 'customerId',
	type: 'resourceLocator',
	default: {
		mode: 'id',
		value: '',
	},
	modes: [
		{
			displayName: 'By ID',
			name: 'id',
			type: 'string',
			placeholder: 'e.g. 12345',
		},
	],
	required: true,
};

export const customerBodyProperties: INodeProperties[] = [
	{
		displayName: 'Customer Organization',
		name: 'customerOrganization',
		type: 'string',
		required: true,
		default: '',
		description: 'Name of the customer organization',
		routing: { send: { type: 'body', property: 'customerOrganization' } },
	},
	{
		displayName: 'Contact Name',
		name: 'customerName',
		type: 'string',
		required: true,
		default: '',
		description: 'Name of the primary contact',
		routing: { send: { type: 'body', property: 'customerName' } },
	},
	{
		displayName: 'Contact Email',
		name: 'customerEmail',
		type: 'string',
		required: true,
		default: '',
		description: 'Email address of the primary contact',
		placeholder: 'name@example.com',
		routing: { send: { type: 'body', property: 'customerEmail' } },
	},
	{
		displayName: 'Language Code',
		name: 'languageCode',
		type: 'string',
		required: true,
		default: '',
		description: 'Preferred language of the customer',
		placeholder: 'en',
		routing: { send: { type: 'body', property: 'languageCode' } },
	},
	{
		displayName: 'Street',
		name: 'street',
		type: 'string',
		required: true,
		default: '',
		description: 'Street address of the customer',
		routing: { send: { type: 'body', property: 'customerAddress.street' } },
	},
	{
		displayName: 'City',
		name: 'city',
		type: 'string',
		required: true,
		default: '',
		description: 'City of the customer address',
		routing: { send: { type: 'body', property: 'customerAddress.city' } },
	},
	{
		displayName: 'State',
		name: 'state',
		type: 'string',
		required: true,
		default: '',
		description: 'State in its short form for the country, for example VA',
		routing: { send: { type: 'body', property: 'customerAddress.state' } },
	},
	{
		displayName: 'Postal Code',
		name: 'zip',
		type: 'string',
		required: true,
		default: '',
		description: 'Postal code of the customer address',
		routing: { send: { type: 'body', property: 'customerAddress.zip' } },
	},
	{
		displayName: 'Country',
		name: 'country',
		type: 'string',
		required: true,
		default: '',
		description: 'Country in its short form, for example US',
		routing: { send: { type: 'body', property: 'customerAddress.country' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		default: {},
		placeholder: 'Add Field',
		options: [
			{
				displayName: 'Contact Phone',
				name: 'customerPhone',
				type: 'string',
				default: '',
				description: 'Phone number of the primary contact',
				routing: { send: { type: 'body', property: 'customerPhone' } },
			},
			{
				displayName: 'Contact Title',
				name: 'customerTitle',
				type: 'string',
				default: '',
				description: 'Title of the primary contact',
				routing: { send: { type: 'body', property: 'customerTitle' } },
			},
			{
				displayName: 'Suite',
				name: 'suite',
				type: 'string',
				default: '',
				description: 'Suite or unit of the customer address',
				routing: { send: { type: 'body', property: 'customerAddress.suite' } },
			},
		],
	},
];

export const providerIdProperty: INodeProperties = {
	displayName: 'Provider ID',
	name: 'providerId',
	type: 'string',
	default: '',
	description: 'Cloud provider ID in CCP',
	routing: { send: { type: 'query', property: 'providerId' } },
};
